# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nativeMqtt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nativeMqtt
  pod 'CocoaMQTT', '2.0.3-beta7'

  target 'nativeMqttTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nativeMqttUITests' do
    # Pods for testing
  end

end
